export enum ContractName {
  MANAToken,
  LANDRegistry,
  LANDProxy,
  Marketplace,
  MarketplaceProxy,
  EstateRegistry,
  EstateProxy,
  ERC721Bid,
  ExclusiveMasksCollection,
  DCLRegistrar,
  DCLControllerV2,
  RentalsProxyAdmin,
  RentalsProxy,
  RentalsImplementation,
  VestingImpl,
  PeriodicTokenVestingImpl,
  VestingFactory,
  BatchVesting,
  OwnableBatchVestingImpl,
  MinimalProxyFactory,
  NAMEDenylist,
  Catalyst,
  POIAllowlist,
  // Polygon contracts
  MarketplaceV2,
  RoyaltiesManager,
  CollectionImplementation,
  CollectionFactoryV3,
  CollectionManager,
  CollectionStore,
  Forwarder,
  Committee,
  Rarities,
  RaritiesWithOracle,
  ChainlinkOracle,
  DummyDataFeed,
  UpgradeableBeacon,
  MetaTxForwarder,
  POI,
  TPR,
  TPRAdmin,
  TPRProxy,
}

export enum ChainId {
  MAINNET = 1,
  GOERLI = 5,
  SEPOLIA = 11155111,
  GANACHE = 1337,
  MATIC = 137,
  MUMBAI = 80001,
  AMOY = 80002
}
